version: 2

updates:
  - &maven
    package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 10
    target-branch: "main"

  - <<: *maven
    target-branch: "2.0"

  - &npm
    package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    groups:
      dev-deps:
        dependency-type: "development"
    target-branch: "main"

  - <<: *npm
    target-branch: "2.0"